// Code generated by structgen DO NOT EDIT

	export enum itfNameKind {
		concret1 = "concret1",
concret2 = "concret2"
	}
	
	export interface itfName {
		Kind: itfNameKind
		Data: concret1 | concret2
	}
// github.com/benoitkugler/structgen/ts-types/test.concret1
export interface concret1 {
	List2: (number[] | null),
	V: number,
}
// github.com/benoitkugler/structgen/ts-types/test.concret2
export interface concret2 {
	D: number,
}
// github.com/benoitkugler/structgen/ts-types/test.ListV
	export type ListV = (itfName[] | null)
// github.com/benoitkugler/structgen/ts-types/test.model
export interface model {
	Value: itfName,
	A: number,
	B: string,
	L: ListV,
	Dict: ({ [key: number]: number } | null),
}
// github.com/benoitkugler/structgen/ts-types/test.node
export interface node {
	Children: (node[] | null),
}
