// Code generated by structgen. DO NOT EDIT

typedef JSON = Map<String, dynamic>; // alias to shorten JSON convertors

int intFromJson(dynamic json) {
  return json as int;
}

dynamic intToJson(int item) {
  return item;
}

DateTime DateTimeFromJson(dynamic json) {
  return DateTime.parse(json as String);
}

dynamic DateTimeToJson(DateTime dt) {
  return dt.toString();
}

String StringFromJson(dynamic json) {
  return json as String;
}

dynamic StringToJson(String item) {
  return item;
}

// github.com/benoitkugler/intendance/server/models.Commande
class Commande {
  final int id;
  final int id_utilisateur;
  final DateTime date_emission;
  final String tag;

  Commande(this.id, this.id_utilisateur, this.date_emission, this.tag);
}

Commande CommandeFromJson(JSON json) {
  return Commande(intFromJson(json['id']), intFromJson(json['id_utilisateur']),
      DateTimeFromJson(json['date_emission']), StringFromJson(json['tag']));
}

JSON CommandeToJson(Commande item) {
  return {
    "id": intToJson(item.id),
    "id_utilisateur": intToJson(item.id_utilisateur),
    "date_emission": DateTimeToJson(item.date_emission),
    "tag": StringToJson(item.tag)
  };
}

// github.com/benoitkugler/intendance/server/models.CommandeProduit
class CommandeProduit {
  final int id_commande;
  final int id_produit;
  final int quantite;

  CommandeProduit(this.id_commande, this.id_produit, this.quantite);
}

CommandeProduit CommandeProduitFromJson(JSON json) {
  return CommandeProduit(intFromJson(json['id_commande']),
      intFromJson(json['id_produit']), intFromJson(json['quantite']));
}

JSON CommandeProduitToJson(CommandeProduit item) {
  return {
    "id_commande": intToJson(item.id_commande),
    "id_produit": intToJson(item.id_produit),
    "quantite": intToJson(item.quantite)
  };
}

// github.com/benoitkugler/intendance/server/models.DefautProduit
class DefautProduit {
  final int id_utilisateur;
  final int id_ingredient;
  final int id_fournisseur;
  final int id_produit;

  DefautProduit(this.id_utilisateur, this.id_ingredient, this.id_fournisseur,
      this.id_produit);
}

DefautProduit DefautProduitFromJson(JSON json) {
  return DefautProduit(
      intFromJson(json['id_utilisateur']),
      intFromJson(json['id_ingredient']),
      intFromJson(json['id_fournisseur']),
      intFromJson(json['id_produit']));
}

JSON DefautProduitToJson(DefautProduit item) {
  return {
    "id_utilisateur": intToJson(item.id_utilisateur),
    "id_ingredient": intToJson(item.id_ingredient),
    "id_fournisseur": intToJson(item.id_fournisseur),
    "id_produit": intToJson(item.id_produit)
  };
}

// github.com/benoitkugler/intendance/server/models.Fournisseur
class Fournisseur {
  final int id;
  final String nom;
  final String lieu;

  Fournisseur(this.id, this.nom, this.lieu);
}

Fournisseur FournisseurFromJson(JSON json) {
  return Fournisseur(intFromJson(json['id']), StringFromJson(json['nom']),
      StringFromJson(json['lieu']));
}

JSON FournisseurToJson(Fournisseur item) {
  return {
    "id": intToJson(item.id),
    "nom": StringToJson(item.nom),
    "lieu": StringToJson(item.lieu)
  };
}

// github.com/benoitkugler/intendance/server/models.Groupe
class Groupe {
  final int id;
  final int id_sejour;
  final String nom;
  final int nb_personnes;
  final String couleur;

  Groupe(this.id, this.id_sejour, this.nom, this.nb_personnes, this.couleur);
}

Groupe GroupeFromJson(JSON json) {
  return Groupe(
      intFromJson(json['id']),
      intFromJson(json['id_sejour']),
      StringFromJson(json['nom']),
      intFromJson(json['nb_personnes']),
      StringFromJson(json['couleur']));
}

JSON GroupeToJson(Groupe item) {
  return {
    "id": intToJson(item.id),
    "id_sejour": intToJson(item.id_sejour),
    "nom": StringToJson(item.nom),
    "nb_personnes": intToJson(item.nb_personnes),
    "couleur": StringToJson(item.couleur)
  };
}

// github.com/benoitkugler/intendance/server/models.Unite
enum Unite { Kilos, Litres, Piece, Zero }

extension __Unite on Unite {
  static const _labels = ["Kilos", "Litres", "Pièce(s)", "Unité invalide"];

  String label() {
    return _labels[this.index];
  }

  static const _values = ["Kg", "L", "P", ""];
  static Unite fromValue(String s) {
    return _values.indexOf(s) as Unite;
  }

  String toValue() {
    return _values[this.index];
  }
}

Unite UniteFromJson(dynamic json) {
  return __Unite.fromValue(json as String);
}

dynamic UniteToJson(Unite item) {
  return item.toValue();
}

// github.com/benoitkugler/intendance/server/models.Categorie
typedef Categorie = String;
Categorie CategorieFromJson(dynamic json) {
  return StringFromJson(json);
}

dynamic CategorieToJson(Categorie item) {
  return StringToJson(item);
}

// github.com/benoitkugler/intendance/server/models.Callories
class Callories {
  Callories();
}

Callories CalloriesFromJson(JSON json) {
  return Callories();
}

JSON CalloriesToJson(Callories item) {
  return {};
}

double doubleFromJson(dynamic json) {
  return json as double;
}

dynamic doubleToJson(double item) {
  return item;
}

// github.com/benoitkugler/intendance/server/models.Conditionnement
class Conditionnement {
  final double quantite;
  final Unite unite;

  Conditionnement(this.quantite, this.unite);
}

Conditionnement ConditionnementFromJson(JSON json) {
  return Conditionnement(
      doubleFromJson(json['quantite']), UniteFromJson(json['unite']));
}

JSON ConditionnementToJson(Conditionnement item) {
  return {
    "quantite": doubleToJson(item.quantite),
    "unite": UniteToJson(item.unite)
  };
}

// github.com/benoitkugler/intendance/server/models.Ingredient
class Ingredient {
  final int id;
  final String nom;
  final Unite unite;
  final Categorie categorie;
  final Callories callories;
  final Conditionnement conditionnement;

  Ingredient(this.id, this.nom, this.unite, this.categorie, this.callories,
      this.conditionnement);
}

Ingredient IngredientFromJson(JSON json) {
  return Ingredient(
      intFromJson(json['id']),
      StringFromJson(json['nom']),
      UniteFromJson(json['unite']),
      CategorieFromJson(json['categorie']),
      CalloriesFromJson(json['callories']),
      ConditionnementFromJson(json['conditionnement']));
}

JSON IngredientToJson(Ingredient item) {
  return {
    "id": intToJson(item.id),
    "nom": StringToJson(item.nom),
    "unite": UniteToJson(item.unite),
    "categorie": CategorieToJson(item.categorie),
    "callories": CalloriesToJson(item.callories),
    "conditionnement": ConditionnementToJson(item.conditionnement)
  };
}

// github.com/benoitkugler/intendance/server/models.IngredientProduit
class IngredientProduit {
  final int id_ingredient;
  final int id_produit;
  final int id_utilisateur;

  IngredientProduit(this.id_ingredient, this.id_produit, this.id_utilisateur);
}

IngredientProduit IngredientProduitFromJson(JSON json) {
  return IngredientProduit(intFromJson(json['id_ingredient']),
      intFromJson(json['id_produit']), intFromJson(json['id_utilisateur']));
}

JSON IngredientProduitToJson(IngredientProduit item) {
  return {
    "id_ingredient": intToJson(item.id_ingredient),
    "id_produit": intToJson(item.id_produit),
    "id_utilisateur": intToJson(item.id_utilisateur)
  };
}

// github.com/benoitkugler/intendance/server/models.LienIngredient
class LienIngredient {
  final int id_ingredient;
  final double quantite;
  final String cuisson;

  LienIngredient(this.id_ingredient, this.quantite, this.cuisson);
}

LienIngredient LienIngredientFromJson(JSON json) {
  return LienIngredient(intFromJson(json['id_ingredient']),
      doubleFromJson(json['quantite']), StringFromJson(json['cuisson']));
}

JSON LienIngredientToJson(LienIngredient item) {
  return {
    "id_ingredient": intToJson(item.id_ingredient),
    "quantite": doubleToJson(item.quantite),
    "cuisson": StringToJson(item.cuisson)
  };
}

bool boolFromJson(dynamic json) {
  return json as bool;
}

dynamic boolToJson(bool item) {
  return item;
}

// github.com/benoitkugler/intendance/server/models.JoursLivraison
typedef JoursLivraison = List<bool>;
JoursLivraison JoursLivraisonFromJson(dynamic json) {
  return (json as List<dynamic>).map(boolFromJson).toList();
}

dynamic JoursLivraisonToJson(JoursLivraison item) {
  return item.map(boolToJson).toList();
}

// github.com/benoitkugler/intendance/server/models.Livraison
class Livraison {
  final int id;
  final int id_fournisseur;
  final String nom;
  final JoursLivraison jours_livraison;
  final int delai_commande;
  final int anticipation;

  Livraison(this.id, this.id_fournisseur, this.nom, this.jours_livraison,
      this.delai_commande, this.anticipation);
}

Livraison LivraisonFromJson(JSON json) {
  return Livraison(
      intFromJson(json['id']),
      intFromJson(json['id_fournisseur']),
      StringFromJson(json['nom']),
      JoursLivraisonFromJson(json['jours_livraison']),
      intFromJson(json['delai_commande']),
      intFromJson(json['anticipation']));
}

JSON LivraisonToJson(Livraison item) {
  return {
    "id": intToJson(item.id),
    "id_fournisseur": intToJson(item.id_fournisseur),
    "nom": StringToJson(item.nom),
    "jours_livraison": JoursLivraisonToJson(item.jours_livraison),
    "delai_commande": intToJson(item.delai_commande),
    "anticipation": intToJson(item.anticipation)
  };
}

// database/sql.NullInt64
class NullInt64 {
  final int Int64;
  final bool Valid;

  NullInt64(this.Int64, this.Valid);
}

NullInt64 NullInt64FromJson(JSON json) {
  return NullInt64(intFromJson(json['Int64']), boolFromJson(json['Valid']));
}

JSON NullInt64ToJson(NullInt64 item) {
  return {"Int64": intToJson(item.Int64), "Valid": boolToJson(item.Valid)};
}

// github.com/benoitkugler/intendance/server/models.Menu
class Menu {
  final int id;
  final NullInt64 id_utilisateur;
  final String commentaire;

  Menu(this.id, this.id_utilisateur, this.commentaire);
}

Menu MenuFromJson(JSON json) {
  return Menu(
      intFromJson(json['id']),
      NullInt64FromJson(json['id_utilisateur']),
      StringFromJson(json['commentaire']));
}

JSON MenuToJson(Menu item) {
  return {
    "id": intToJson(item.id),
    "id_utilisateur": NullInt64ToJson(item.id_utilisateur),
    "commentaire": StringToJson(item.commentaire)
  };
}

// github.com/benoitkugler/intendance/server/models.MenuIngredient
class MenuIngredient {
  final int id_menu;

  MenuIngredient(this.id_menu);
}

MenuIngredient MenuIngredientFromJson(JSON json) {
  return MenuIngredient(intFromJson(json['id_menu']));
}

JSON MenuIngredientToJson(MenuIngredient item) {
  return {"id_menu": intToJson(item.id_menu)};
}

// github.com/benoitkugler/intendance/server/models.MenuRecette
class MenuRecette {
  final int id_menu;
  final int id_recette;

  MenuRecette(this.id_menu, this.id_recette);
}

MenuRecette MenuRecetteFromJson(JSON json) {
  return MenuRecette(
      intFromJson(json['id_menu']), intFromJson(json['id_recette']));
}

JSON MenuRecetteToJson(MenuRecette item) {
  return {
    "id_menu": intToJson(item.id_menu),
    "id_recette": intToJson(item.id_recette)
  };
}

// github.com/benoitkugler/intendance/server/models.Produit
class Produit {
  final int id;
  final int id_livraison;
  final String nom;
  final Conditionnement conditionnement;
  final double prix;
  final String reference_fournisseur;
  final int colisage;

  Produit(this.id, this.id_livraison, this.nom, this.conditionnement, this.prix,
      this.reference_fournisseur, this.colisage);
}

Produit ProduitFromJson(JSON json) {
  return Produit(
      intFromJson(json['id']),
      intFromJson(json['id_livraison']),
      StringFromJson(json['nom']),
      ConditionnementFromJson(json['conditionnement']),
      doubleFromJson(json['prix']),
      StringFromJson(json['reference_fournisseur']),
      intFromJson(json['colisage']));
}

JSON ProduitToJson(Produit item) {
  return {
    "id": intToJson(item.id),
    "id_livraison": intToJson(item.id_livraison),
    "nom": StringToJson(item.nom),
    "conditionnement": ConditionnementToJson(item.conditionnement),
    "prix": doubleToJson(item.prix),
    "reference_fournisseur": StringToJson(item.reference_fournisseur),
    "colisage": intToJson(item.colisage)
  };
}

// github.com/benoitkugler/intendance/server/models.Recette
class Recette {
  final int id;
  final NullInt64 id_utilisateur;
  final String nom;
  final String mode_emploi;

  Recette(this.id, this.id_utilisateur, this.nom, this.mode_emploi);
}

Recette RecetteFromJson(JSON json) {
  return Recette(
      intFromJson(json['id']),
      NullInt64FromJson(json['id_utilisateur']),
      StringFromJson(json['nom']),
      StringFromJson(json['mode_emploi']));
}

JSON RecetteToJson(Recette item) {
  return {
    "id": intToJson(item.id),
    "id_utilisateur": NullInt64ToJson(item.id_utilisateur),
    "nom": StringToJson(item.nom),
    "mode_emploi": StringToJson(item.mode_emploi)
  };
}

// github.com/benoitkugler/intendance/server/models.RecetteIngredient
class RecetteIngredient {
  final int id_recette;

  RecetteIngredient(this.id_recette);
}

RecetteIngredient RecetteIngredientFromJson(JSON json) {
  return RecetteIngredient(intFromJson(json['id_recette']));
}

JSON RecetteIngredientToJson(RecetteIngredient item) {
  return {"id_recette": intToJson(item.id_recette)};
}

// github.com/benoitkugler/intendance/server/models.Horaire
enum Horaire { Cinquieme, Diner, Gouter, Midi, PetitDejeuner }

extension __Horaire on Horaire {
  static const _labels = [
    "Cinquième",
    "Dîner",
    "Goûter",
    "Midi",
    "Petit déjeuner"
  ];

  String label() {
    return _labels[this.index];
  }

  static Horaire fromValue(int i) {
    return i as Horaire;
  }

  int toValue() {
    return this.index;
  }
}

Horaire HoraireFromJson(dynamic json) {
  return __Horaire.fromValue(json as int);
}

dynamic HoraireToJson(Horaire item) {
  return item.toValue();
}

// github.com/benoitkugler/intendance/server/models.Repas
class Repas {
  final int id;
  final int id_sejour;
  final int offset_personnes;
  final int jour_offset;
  final Horaire horaire;
  final int anticipation;

  Repas(this.id, this.id_sejour, this.offset_personnes, this.jour_offset,
      this.horaire, this.anticipation);
}

Repas RepasFromJson(JSON json) {
  return Repas(
      intFromJson(json['id']),
      intFromJson(json['id_sejour']),
      intFromJson(json['offset_personnes']),
      intFromJson(json['jour_offset']),
      HoraireFromJson(json['horaire']),
      intFromJson(json['anticipation']));
}

JSON RepasToJson(Repas item) {
  return {
    "id": intToJson(item.id),
    "id_sejour": intToJson(item.id_sejour),
    "offset_personnes": intToJson(item.offset_personnes),
    "jour_offset": intToJson(item.jour_offset),
    "horaire": HoraireToJson(item.horaire),
    "anticipation": intToJson(item.anticipation)
  };
}

// github.com/benoitkugler/intendance/server/models.RepasGroupe
class RepasGroupe {
  final int id_repas;
  final int id_groupe;

  RepasGroupe(this.id_repas, this.id_groupe);
}

RepasGroupe RepasGroupeFromJson(JSON json) {
  return RepasGroupe(
      intFromJson(json['id_repas']), intFromJson(json['id_groupe']));
}

JSON RepasGroupeToJson(RepasGroupe item) {
  return {
    "id_repas": intToJson(item.id_repas),
    "id_groupe": intToJson(item.id_groupe)
  };
}

// github.com/benoitkugler/intendance/server/models.RepasIngredient
class RepasIngredient {
  final int id_repas;

  RepasIngredient(this.id_repas);
}

RepasIngredient RepasIngredientFromJson(JSON json) {
  return RepasIngredient(intFromJson(json['id_repas']));
}

JSON RepasIngredientToJson(RepasIngredient item) {
  return {"id_repas": intToJson(item.id_repas)};
}

// github.com/benoitkugler/intendance/server/models.RepasRecette
class RepasRecette {
  final int id_repas;
  final int id_recette;

  RepasRecette(this.id_repas, this.id_recette);
}

RepasRecette RepasRecetteFromJson(JSON json) {
  return RepasRecette(
      intFromJson(json['id_repas']), intFromJson(json['id_recette']));
}

JSON RepasRecetteToJson(RepasRecette item) {
  return {
    "id_repas": intToJson(item.id_repas),
    "id_recette": intToJson(item.id_recette)
  };
}

// github.com/benoitkugler/intendance/server/models.Sejour
class Sejour {
  final int id;
  final int id_utilisateur;
  final DateTime date_debut;
  final String nom;

  Sejour(this.id, this.id_utilisateur, this.date_debut, this.nom);
}

Sejour SejourFromJson(JSON json) {
  return Sejour(intFromJson(json['id']), intFromJson(json['id_utilisateur']),
      DateTimeFromJson(json['date_debut']), StringFromJson(json['nom']));
}

JSON SejourToJson(Sejour item) {
  return {
    "id": intToJson(item.id),
    "id_utilisateur": intToJson(item.id_utilisateur),
    "date_debut": DateTimeToJson(item.date_debut),
    "nom": StringToJson(item.nom)
  };
}

// github.com/benoitkugler/intendance/server/models.SejourFournisseur
class SejourFournisseur {
  final int id_utilisateur;
  final int id_sejour;
  final int id_fournisseur;

  SejourFournisseur(this.id_utilisateur, this.id_sejour, this.id_fournisseur);
}

SejourFournisseur SejourFournisseurFromJson(JSON json) {
  return SejourFournisseur(intFromJson(json['id_utilisateur']),
      intFromJson(json['id_sejour']), intFromJson(json['id_fournisseur']));
}

JSON SejourFournisseurToJson(SejourFournisseur item) {
  return {
    "id_utilisateur": intToJson(item.id_utilisateur),
    "id_sejour": intToJson(item.id_sejour),
    "id_fournisseur": intToJson(item.id_fournisseur)
  };
}

// github.com/benoitkugler/intendance/server/models.Utilisateur
class Utilisateur {
  final int id;
  final String password;
  final String mail;
  final String prenom_nom;

  Utilisateur(this.id, this.password, this.mail, this.prenom_nom);
}

Utilisateur UtilisateurFromJson(JSON json) {
  return Utilisateur(intFromJson(json['id']), StringFromJson(json['password']),
      StringFromJson(json['mail']), StringFromJson(json['prenom_nom']));
}

JSON UtilisateurToJson(Utilisateur item) {
  return {
    "id": intToJson(item.id),
    "password": StringToJson(item.password),
    "mail": StringToJson(item.mail),
    "prenom_nom": StringToJson(item.prenom_nom)
  };
}

// github.com/benoitkugler/intendance/server/models.UtilisateurFournisseur
class UtilisateurFournisseur {
  final int id_utilisateur;
  final int id_fournisseur;

  UtilisateurFournisseur(this.id_utilisateur, this.id_fournisseur);
}

UtilisateurFournisseur UtilisateurFournisseurFromJson(JSON json) {
  return UtilisateurFournisseur(
      intFromJson(json['id_utilisateur']), intFromJson(json['id_fournisseur']));
}

JSON UtilisateurFournisseurToJson(UtilisateurFournisseur item) {
  return {
    "id_utilisateur": intToJson(item.id_utilisateur),
    "id_fournisseur": intToJson(item.id_fournisseur)
  };
}
