// Code generated by structgen. DO NOT EDIT

typedef JSON = Map<String, dynamic>; // alias to shorten JSON convertors

double doubleFromJson(dynamic json) {
  return json as double;
}

dynamic doubleToJson(double item) {
  return item;
}

// github.com/benoitkugler/structgen/dart-types/test.b
class b {
  final double D;

  b(this.D);
}

b bFromJson(JSON json) {
  return b(doubleFromJson(json['D']));
}

JSON bToJson(b item) {
  return {"D": doubleToJson(item.D)};
}

// github.com/benoitkugler/structgen/dart-types/test.i
typedef i = dynamic;
i iFromJson(dynamic json) {
  return dynamicFromJson(json);
}

dynamic iToJson(i item) {
  return dynamicToJson(item);
}

int intFromJson(dynamic json) {
  return json as int;
}

dynamic intToJson(int item) {
  return item;
}

// github.com/benoitkugler/structgen/dart-types/test.model
class model {
  final int A;
  final i Value;

  model(this.A, this.Value);
}

model modelFromJson(JSON json) {
  return model(intFromJson(json['A']), iFromJson(json['Value']));
}

JSON modelToJson(model item) {
  return {"A": intToJson(item.A), "Value": iToJson(item.Value)};
}

// github.com/benoitkugler/structgen/dart-types/test.s
class s {
  final int V;

  s(this.V);
}

s sFromJson(JSON json) {
  return s(intFromJson(json['V']));
}

JSON sToJson(s item) {
  return {"V": intToJson(item.V)};
}
